/* vw_frontend.h -- the text front end: generated by tools/mkfront.py. */
#ifndef VW_FRONTEND_H
#define VW_FRONTEND_H

/* OrthToPhon.c */
int16_t DecompressString(Ptr dest, unsigned char *src);
void AddPhon(FETokenPtr tok, int16_t phon);
void Store_S_or_Z(synthVarsPtr xx, FETokenPtr tok);
void Consonant_Doubling_Adjust(unsigned char *wordPtr);
int16_t Decompose_E_Common(synthVarsPtr xx, FETokenPtr tok);
int16_t Decompose_I_Common(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_IZING_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_IZINGS_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_IZER_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_IZERS_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_IZE_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_IZED_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_IZES_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_INESS_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_INESSES_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_NESS_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_NESSES_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_ISM_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_ISMS_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_OR_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_ORS_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_BLY_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_CALLY_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_LY_Morph(synthVarsPtr xx, FETokenPtr tok);
void Do_ED_Morph(synthVarsPtr xx, FETokenPtr tok);
void Do_ER_Morph(synthVarsPtr xx, FETokenPtr tok);
void Do_ERS_Morph(synthVarsPtr xx, FETokenPtr tok);
void Do_EST_Morph(synthVarsPtr xx, FETokenPtr tok);
void Do_IED_Morph(synthVarsPtr xx, FETokenPtr tok);
void Do_IER_Morph(synthVarsPtr xx, FETokenPtr tok);
void Do_IERS_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_IEST_Morph(synthVarsPtr xx, FETokenPtr tok);
void Do_ING_Morph(synthVarsPtr xx, FETokenPtr tok);
void Do_INGS_Morph(synthVarsPtr xx, FETokenPtr tok);
void Do_IMENT_Morph(synthVarsPtr xx, FETokenPtr tok);
void Do_IMENTS_Morph(synthVarsPtr xx, FETokenPtr tok);
void Do_ABLE_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_MENT_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_MENTS_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_IES_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_ES_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_S_Morph(synthVarsPtr xx, FETokenPtr tok);
void Do_IN_Morph(synthVarsPtr xx, FETokenPtr tok);
void Do_INS_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_IZIN_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Do_IZINS_Morph(synthVarsPtr xx, FETokenPtr tok);
int16_t Search_Suffix(synthVarsPtr xx, unsigned char *wordPtr);
int16_t DoMorph(synthVarsPtr xx, FETokenPtr tok);
void EngToP(synthVarsPtr xx, char *inalpha, char *phon);
int16_t FindConsonant(synthVarsPtr xx, unsigned char **p_i_ptr);
int16_t FindSibilant(synthVarsPtr xx, unsigned char **p_i_ptr);
int16_t FindVowel(synthVarsPtr xx, unsigned char **p_i_ptr);
int16_t search_special(synthVarsPtr xx, unsigned char **p_i_ptr, unsigned char *sprule);
unsigned char *dorule(synthVarsPtr xx, unsigned char *i_ptr, unsigned char *r_ptr);
int16_t OrthToPhon(synthVarsPtr xx, ConvertTextRecPtr tRec, int16_t dictFile);

/* ParsePhons.c */
int16_t GetPhon_FE(synthVarsPtr xx, int16_t index);
int16_t GetPhonCtrl_FE(synthVarsPtr xx, int16_t index);
void Insert_Closure_Release(synthVarsPtr xx);
void Mod_Duration_FE(synthVarsPtr xx);
void Fill_Phon_Buf_2(synthVarsPtr xx);
void Fill_Phon_Buf_2A(synthVarsPtr xx);
int16_t If_Consonant_Cluster(int16_t Consonant_1st, int16_t Consonant_2nd);
int16_t Find_Next_Word_Bound(synthVarsPtr xx, int16_t index);
void MarkSyllableStart(synthVarsPtr xx);
void Place_Stress_In_Consonant(synthVarsPtr xx, int16_t scanIndex);
void MarkSyllable(synthVarsPtr xx, int16_t scanIndex);
void MarkBoundry(synthVarsPtr xx, int16_t scanIndex);
void Flag_PhonBuf_1(synthVarsPtr xx);
void Store_Phon_In_PhonBuf_1(synthVarsPtr xx, int16_t phon);
void Init_Rate_Params(synthVarsPtr xx);
void FindNotes(synthVarsPtr xx);
int16_t MakeSpeechData(synthVarsPtr xx, unsigned char *targetVocals, unsigned char *targetTrack, Handle speechData, int32_t *speechDataLen, int32_t rate);
int16_t Collect_Phons(synthVarsPtr xx);
void TunePhons(synthVarsPtr xx);
int16_t AdjustBoundryPhons(synthVarsPtr xx, unsigned char *targetVocals, unsigned char *targetTrack, int32_t startTime, int32_t endTime, int32_t flags);

/* Music.c */
int16_t GetNextTrackEvent(MIDI_EventPtr me, int16_t trackNum);

#endif /* VW_FRONTEND_H */
