/* Generated by tools/genheader.py from the STABS records of
   VocalWriter 2.0.1; do not edit. Layouts are the original's. */
#ifndef VW_TYPES_H
#define VW_TYPES_H
#include <stdint.h>
#include <stddef.h>

typedef float rShort;        /* the engine's "real short": a float */
typedef float rLong;
typedef float rUSC;
typedef float rUSShort;
typedef float mFloat;
typedef int32_t Fixed;
typedef int32_t SInt32;
typedef int16_t SInt16;
typedef uint32_t UInt32;
typedef uint16_t UInt16;
typedef unsigned char UInt8;
typedef int16_t OSErr;
typedef char *Ptr;
typedef char **Handle;

typedef struct ControlBlock ControlBlock;
typedef struct Frame Frame;
typedef struct voiceData voiceData;
typedef struct formantVar formantVar;
typedef struct VCB_Gen VCB_Gen;
typedef struct VoiceCtrlBlock VoiceCtrlBlock;
typedef struct DOC_Regs DOC_Regs;
typedef struct MIDI_Item MIDI_Item;
typedef struct REVERBMOD REVERBMOD;
typedef struct MIDI_Dur_Type MIDI_Dur_Type;
typedef struct WaveList WaveList;
typedef struct OCB OCB;
typedef struct synthVars synthVars;
typedef struct Float80 Float80;
typedef struct ExtSoundHeader ExtSoundHeader;
typedef struct SndCommand SndCommand;
typedef struct DeferredTask DeferredTask;
typedef struct UnsignedWide UnsignedWide;
typedef struct TMTask TMTask;
typedef struct TMinfo TMinfo;
typedef struct shellVar shellVar;
typedef struct REVERBCONFIG REVERBCONFIG;
typedef struct PhonSyllableRec PhonSyllableRec;
typedef struct ConvertTextRec ConvertTextRec;
typedef struct FEToken FEToken;
typedef struct MIDI_Event MIDI_Event;
typedef struct Dict Dict;
typedef struct WaveDef WaveDef;
typedef struct TrackInfo TrackInfo;
typedef struct SeqInfo SeqInfo;
typedef uint32_t UnsignedFixed;
typedef Float80 extended80;
typedef void *QElemPtr;
typedef void (*DeferredTaskUPP)(void);
typedef void (*DeferredTaskProcPtr)(void);
typedef void (*TimerUPP)(void);
typedef void (*TimerProcPtr)(void);
typedef void *SndChannelPtr;
typedef void (*SndCallBackUPP)(void);
typedef void (*SndCallBackProcPtr)(void);
typedef void (*SeqErrorUPP)(void);
typedef void (*SeqErrorProcPtr)(void);
typedef void (*SeqItemUPP)(void);
typedef void (*SeqItemProcPtr)(void);
typedef void (*SeqMarkUPP)(void);
typedef void (*SeqMarkProcPtr)(void);
typedef void (*TempoUPP)(void);
typedef void (*TempoProcPtr)(void);
typedef void (*BeatUPP)(void);
typedef void (*BeatProcPtr)(void);
typedef void (*SeqDoneUPP)(void);
typedef void (*SeqDoneProcPtr)(void);
typedef void (*MeterUPP)(void);
typedef void (*MeterProcPtr)(void);
typedef void (*OverloadUPP)(void);
typedef void (*OverloadProcPtr)(void);
typedef void (*KaraUPP)(void);
typedef void (*KaraProcPtr)(void);
typedef void *TMinfoPtr;
typedef void (*OMSOutUPP)(void);
typedef void (*OMSOutProcPtr)(void);
typedef void *IndexEntry;
typedef formantVar *formantVarPtr;
typedef voiceData *voiceDataPtr;
typedef synthVars *synthVarsPtr;
typedef Frame *FramePtr;
typedef WaveDef *WaveDefPtr;
typedef SeqInfo *SeqInfoPtr;
typedef shellVar *shellVarPtr;
typedef void (*_i_CvtSMFProg_Ptr)(void);
typedef FEToken *FETokenPtr;
typedef ConvertTextRec *ConvertTextRecPtr;
typedef MIDI_Event *MIDI_EventPtr;
typedef MIDI_Item *MIDI_ItemPtr;

struct ControlBlock {  /* 36 bytes in the original */
    int16_t curP_START_Targ;  /* +0x0 */
    int16_t curTarget_TIME;  /* +0x2 */
    int16_t curTarget_STEP;  /* +0x4 */
    int16_t curTarget_OFFS;  /* +0x6 */
    int16_t HEAD_offs;  /* +0x8 */
    int16_t HEAD_step;  /* +0xa */
    int16_t TAIL_offs;  /* +0xc */
    int16_t TAIL_step;  /* +0xe */
    int16_t TAIL_START_time;  /* +0x10 */
    int16_t onset_END_TIME;  /* +0x12 */
    int16_t onset_VAL;  /* +0x14 */
    int16_t nextP_START_Targ;  /* +0x16 */
    int16_t prevP_END_Targ;  /* +0x18 */
    int16_t curP_END_Targ;  /* +0x1a */
    int16_t *ptrToTargetList;  /* +0x1c */
    int16_t lastVal;  /* +0x20 */
};

struct Frame {  /* 52 bytes in the original */
    int16_t Av;  /* +0x0 */
    int16_t Af;  /* +0x2 */
    int16_t f0;  /* +0x4 */
    int16_t f1;  /* +0x6 */
    int16_t f2;  /* +0x8 */
    int16_t f3;  /* +0xa */
    int16_t a2;  /* +0xc */
    int16_t a3;  /* +0xe */
    int16_t a4;  /* +0x10 */
    int16_t a5;  /* +0x12 */
    int16_t a6;  /* +0x14 */
    int16_t FNZ;  /* +0x16 */
    int16_t AB;  /* +0x18 */
    int16_t bw1;  /* +0x1a */
    int16_t bw2;  /* +0x1c */
    int16_t bw3;  /* +0x1e */
    int16_t phon_Edge;  /* +0x20 */
    int32_t marker;  /* +0x24 */
    rShort velocity;  /* +0x28 */
    int16_t f1Gain;  /* +0x2c */
    int16_t f2Gain;  /* +0x2e */
    int16_t f3Gain;  /* +0x30 */
};

struct voiceData {  /* 336 bytes in the original */
    unsigned char voiceName[16];  /* +0x0 */
    int16_t voice;  /* +0x10 */
    int16_t vGain;  /* +0x12 */
    int16_t aGain;  /* +0x14 */
    int16_t aCycle;  /* +0x16 */
    int16_t f4_Freq;  /* +0x18 */
    int16_t f4_BW;  /* +0x1a */
    int16_t f5_Freq;  /* +0x1c */
    int16_t f5_BW;  /* +0x1e */
    int16_t f4p_Freq;  /* +0x20 */
    int16_t f4p_BW;  /* +0x22 */
    int16_t f5p_Freq;  /* +0x24 */
    int16_t f5p_BW;  /* +0x26 */
    int16_t f6p_Freq;  /* +0x28 */
    int16_t f6p_BW;  /* +0x2a */
    int16_t nasal_Base;  /* +0x2c */
    int16_t nasal_targ;  /* +0x2e */
    int16_t nasal_BW;  /* +0x30 */
    int16_t locus;  /* +0x32 */
    int16_t bwGain1;  /* +0x34 */
    int16_t bwGain2;  /* +0x36 */
    int16_t bwGain3;  /* +0x38 */
    int16_t f1_Offset;  /* +0x3a */
    int16_t f2_Offset;  /* +0x3c */
    int16_t f3_Offset;  /* +0x3e */
    int16_t chorus;  /* +0x40 */
    int16_t nGain;  /* +0x42 */
    int16_t sPitch;  /* +0x44 */
    int16_t sGain;  /* +0x46 */
    int16_t AsperW;  /* +0x48 */
    int16_t waveType;  /* +0x4a */
    int16_t vWave[48];  /* +0x4c */
    int16_t vWave1[48];  /* +0xac */
    int16_t customForm;  /* +0x10c */
    int16_t nasalAmt;  /* +0x10e */
    int16_t emphVoice;  /* +0x110 */
    int16_t rvbDelay;  /* +0x112 */
    int16_t rvbDepth;  /* +0x114 */
    int16_t voiceVers;  /* +0x116 */
    int16_t waveRefA;  /* +0x118 */
    int16_t octTuneA;  /* +0x11a */
    int16_t semiTuneA;  /* +0x11c */
    int16_t fineTuneA;  /* +0x11e */
    int16_t oscVolA;  /* +0x120 */
    int16_t waveRefB;  /* +0x122 */
    int16_t octTuneB;  /* +0x124 */
    int16_t semiTuneB;  /* +0x126 */
    int16_t fineTuneB;  /* +0x128 */
    int16_t oscVolB;  /* +0x12a */
    int16_t oscMode;  /* +0x12c */
    int16_t sync;  /* +0x12e */
    int32_t free1;  /* +0x130 */
    int32_t free2;  /* +0x134 */
    int32_t free3;  /* +0x138 */
    int32_t free4;  /* +0x13c */
    int32_t free5;  /* +0x140 */
    int32_t free6;  /* +0x144 */
    int32_t free7;  /* +0x148 */
    int32_t free8;  /* +0x14c */
};

struct formantVar {  /* 4396 bytes in the original */
    int16_t *EnvelopeListTbl;  /* +0x0 */
    int16_t *f1FreqTblM;  /* +0x4 */
    int16_t *f2FreqTblM;  /* +0x8 */
    int16_t *f3FreqTblM;  /* +0xc */
    int16_t *b1FreqTblM;  /* +0x10 */
    int16_t *b2FreqTblM;  /* +0x14 */
    int16_t *b3FreqTblM;  /* +0x18 */
    int16_t *avVolTblM;  /* +0x1c */
    int16_t *f1FreqTblF;  /* +0x20 */
    int16_t *f2FreqTblF;  /* +0x24 */
    int16_t *f3FreqTblF;  /* +0x28 */
    int16_t *b1FreqTblF;  /* +0x2c */
    int16_t *b2FreqTblF;  /* +0x30 */
    int16_t *b3FreqTblF;  /* +0x34 */
    int16_t *avVolTblF;  /* +0x38 */
    int16_t *CtrlBlockTypeTbl;  /* +0x3c */
    int16_t *DefaultTargTbl;  /* +0x40 */
    int16_t *Rank_FWD_Tbl;  /* +0x44 */
    int16_t *Rank_BKWD_Tbl;  /* +0x48 */
    int16_t *NoiseIndexTbl;  /* +0x4c */
    int16_t *Front_Loci_Tbl;  /* +0x50 */
    int16_t *Mid_Loci_Tbl;  /* +0x54 */
    int16_t *Back_Loci_Tbl;  /* +0x58 */
    int16_t *Male_NoiseAmpTbl;  /* +0x5c */
    int16_t *Female_NoiseAmpTbl;  /* +0x60 */
    int16_t *Male_Loci_Tbl;  /* +0x64 */
    int16_t *Female_Loci_Tbl;  /* +0x68 */
    int16_t *BurstDurTbl;  /* +0x6c */
    int32_t *One_Over_X_Tbl;  /* +0x70 */
    int16_t *IntEnvelopeListTbl;  /* +0x74 */
    int16_t *a_EnvelopeListTbl;  /* +0x78 */
    int16_t *a_f1FreqTblM;  /* +0x7c */
    int16_t *a_f2FreqTblM;  /* +0x80 */
    int16_t *a_f3FreqTblM;  /* +0x84 */
    int16_t *a_b1FreqTblM;  /* +0x88 */
    int16_t *a_b2FreqTblM;  /* +0x8c */
    int16_t *a_b3FreqTblM;  /* +0x90 */
    int16_t *a_avVolTblM;  /* +0x94 */
    int16_t *voice_Formants[6];  /* +0x98 */
    int16_t *voice_av_Tbl;  /* +0xb0 */
    int16_t *voice_NoiseAmp_Tbl;  /* +0xb4 */
    int16_t *voice_Locus_Tbl;  /* +0xb8 */
    int16_t *maxDurTbl;  /* +0xbc */
    int16_t *minDurTbl;  /* +0xc0 */
    int16_t locusOffset;  /* +0xc4 */
    int16_t cur_Phon_MaxDur_CF;  /* +0xc6 */
    int32_t cur_Phon_PctOfMaxDur_CF;  /* +0xc8 */
    int32_t cur_Phon_PctOfMaxDur1_CF;  /* +0xcc */
    int32_t cur_Phon_PctOfMaxDur2_CF;  /* +0xd0 */
    int16_t trans_TIME;  /* +0xd4 */
    int16_t trans_LEVEL;  /* +0xd6 */
    int16_t trans_TIME_f2;  /* +0xd8 */
    int16_t trans_LEVEL_f2;  /* +0xda */
    int16_t f2_HEAD_offset;  /* +0xdc */
    int16_t f2_HEAD_step;  /* +0xde */
    int16_t f2_TAIL_START_time;  /* +0xe0 */
    int16_t f2_TAIL_offset;  /* +0xe2 */
    int16_t f2_TAIL_step;  /* +0xe4 */
    int16_t big_Bang;  /* +0xe6 */
    int16_t cur_ControlBlk_Index;  /* +0xe8 */
    ControlBlock controlBlockArray[15];  /* +0xec */
    int16_t controlData[15];  /* +0x308 */
    int16_t diphEntryArray[100];  /* +0x326 */
    int16_t *next_DiphEntry;  /* +0x3f0 */
    Frame frameBuf1;  /* +0x3f4 */
    Frame frameBuf2;  /* +0x428 */
    int16_t curFrameBuf;  /* +0x45c */
    int16_t glotType;  /* +0x45e */
    rShort voiceWaveform[256];  /* +0x460 */
    rShort voiceWaveform1[256];  /* +0x860 */
    rShort *SineWave15Ptr;  /* +0xc60 */
    Fixed glotInc;  /* +0xc64 */
    Fixed glotInc1;  /* +0xc68 */
    Fixed glotIndex;  /* +0xc6c */
    Fixed glotIndex1;  /* +0xc70 */
    int32_t noiseIndex;  /* +0xc74 */
    rShort setNoiseGain;  /* +0xc78 */
    int16_t sync_On_Vowel;  /* +0xc7c */
    rLong ampStep;  /* +0xc80 */
    rLong lastAmp;  /* +0xc84 */
    rLong curAmp_Full;  /* +0xc88 */
    rShort curAmp;  /* +0xc8c */
    rShort Af;  /* +0xc90 */
    rShort Av;  /* +0xc94 */
    rShort wavesampleGain;  /* +0xc98 */
    rShort breathGain;  /* +0xc9c */
    rShort breathGainCtrl;  /* +0xca0 */
    int16_t breathCycle;  /* +0xca4 */
    rUSC *breathWave;  /* +0xca8 */
    int16_t voiceF1Gain;  /* +0xcac */
    int16_t voiceF2Gain;  /* +0xcae */
    int16_t voiceF3Gain;  /* +0xcb0 */
    int32_t voiceBWgain1;  /* +0xcb4 */
    int32_t voiceBWgain2;  /* +0xcb8 */
    int32_t voiceBWgain3;  /* +0xcbc */
    int16_t voiceMinBW;  /* +0xcc0 */
    int16_t voice_F4_Freq;  /* +0xcc2 */
    int16_t voice_F4_BW;  /* +0xcc4 */
    int16_t voice_F5_Freq;  /* +0xcc6 */
    int16_t voice_F5_BW;  /* +0xcc8 */
    int16_t voiceChorus;  /* +0xcca */
    int16_t chorusBase;  /* +0xccc */
    int16_t chorusOffs;  /* +0xcce */
    rShort voiceNoiseGain;  /* +0xcd0 */
    rShort noiseScale;  /* +0xcd4 */
    int16_t f4_Par;  /* +0xcd8 */
    int16_t bw4_Par;  /* +0xcda */
    int16_t f5_Par;  /* +0xcdc */
    int16_t bw5_Par;  /* +0xcde */
    int16_t f6_Par;  /* +0xce0 */
    int16_t bw6_Par;  /* +0xce2 */
    int16_t fNP;  /* +0xce4 */
    int16_t bNP;  /* +0xce6 */
    int16_t nasalBaseFreq;  /* +0xce8 */
    int16_t nasalTargFreq;  /* +0xcea */
    int16_t nasalAmt;  /* +0xcec */
    int16_t hfEmph;  /* +0xcee */
    rShort emphA;  /* +0xcf0 */
    rShort emphB;  /* +0xcf4 */
    int16_t voice_Num;  /* +0xcf8 */
    int32_t *FormTables;  /* +0xcfc */
    rShort *CosTblPtr;  /* +0xd00 */
    rShort *BcoeffTblPtr;  /* +0xd04 */
    rShort *CcoeffTblPtr;  /* +0xd08 */
    Fixed *TOPtr;  /* +0xd0c */
    rUSC *NoiseWavePtr;  /* +0xd10 */
    rUSC *BandNoisePtr;  /* +0xd14 */
    rUSC *HPNoisePtr;  /* +0xd18 */
    rShort Acoeff1;  /* +0xd1c */
    rShort Bcoeff1;  /* +0xd20 */
    rShort Ccoeff1;  /* +0xd24 */
    rShort Acoeff2;  /* +0xd28 */
    rShort Bcoeff2;  /* +0xd2c */
    rShort Ccoeff2;  /* +0xd30 */
    rShort Acoeff3;  /* +0xd34 */
    rShort Bcoeff3;  /* +0xd38 */
    rShort Ccoeff3;  /* +0xd3c */
    rShort Acoeff4;  /* +0xd40 */
    rShort Bcoeff4;  /* +0xd44 */
    rShort Ccoeff4;  /* +0xd48 */
    rShort Acoeff5x;  /* +0xd4c */
    rShort Bcoeff5x;  /* +0xd50 */
    rShort Ccoeff5x;  /* +0xd54 */
    rShort Acoeff4p;  /* +0xd58 */
    rShort Bcoeff4p;  /* +0xd5c */
    rShort Ccoeff4p;  /* +0xd60 */
    rShort Acoeff5;  /* +0xd64 */
    rShort Bcoeff5;  /* +0xd68 */
    rShort Ccoeff5;  /* +0xd6c */
    rShort Acoeff6;  /* +0xd70 */
    rShort Bcoeff6;  /* +0xd74 */
    rShort Ccoeff6;  /* +0xd78 */
    rShort AcoeffNZ;  /* +0xd7c */
    rShort BcoeffNZ;  /* +0xd80 */
    rShort CcoeffNZ;  /* +0xd84 */
    rShort AcoeffNP;  /* +0xd88 */
    rShort BcoeffNP;  /* +0xd8c */
    rShort CcoeffNP;  /* +0xd90 */
    rShort lastAcoeff1;  /* +0xd94 */
    rShort Acoeff1Step;  /* +0xd98 */
    rShort lastBcoeff1;  /* +0xd9c */
    rShort Bcoeff1Step;  /* +0xda0 */
    rShort lastCcoeff1;  /* +0xda4 */
    rShort Ccoeff1Step;  /* +0xda8 */
    rShort lastAcoeff2;  /* +0xdac */
    rShort Acoeff2Step;  /* +0xdb0 */
    rShort lastBcoeff2;  /* +0xdb4 */
    rShort Bcoeff2Step;  /* +0xdb8 */
    rShort lastCcoeff2;  /* +0xdbc */
    rShort Ccoeff2Step;  /* +0xdc0 */
    rShort lastAcoeff3;  /* +0xdc4 */
    rShort Acoeff3Step;  /* +0xdc8 */
    rShort lastBcoeff3;  /* +0xdcc */
    rShort Bcoeff3Step;  /* +0xdd0 */
    rShort lastCcoeff3;  /* +0xdd4 */
    rShort Ccoeff3Step;  /* +0xdd8 */
    int16_t CoeffCntr;  /* +0xddc */
    rShort Na1;  /* +0xde0 */
    rShort Nb1;  /* +0xde4 */
    rShort Na2;  /* +0xde8 */
    rShort Nb2;  /* +0xdec */
    rShort Na3;  /* +0xdf0 */
    rShort Nb3;  /* +0xdf4 */
    rShort Na4;  /* +0xdf8 */
    rShort Nb4;  /* +0xdfc */
    rShort Nx5;  /* +0xe00 */
    rShort Ny5;  /* +0xe04 */
    rShort Na5;  /* +0xe08 */
    rShort Nb5;  /* +0xe0c */
    rShort Na6;  /* +0xe10 */
    rShort Nb6;  /* +0xe14 */
    rShort Na2a;  /* +0xe18 */
    rShort Nb2a;  /* +0xe1c */
    rShort Na3a;  /* +0xe20 */
    rShort Nb3a;  /* +0xe24 */
    rShort Na4a;  /* +0xe28 */
    rShort Nb4a;  /* +0xe2c */
    rShort NaNZ;  /* +0xe30 */
    rShort NbNZ;  /* +0xe34 */
    rShort NaNP;  /* +0xe38 */
    rShort NbNP;  /* +0xe3c */
    rShort amp2;  /* +0xe40 */
    rShort amp3;  /* +0xe44 */
    rShort amp4;  /* +0xe48 */
    rShort amp5;  /* +0xe4c */
    rShort amp6;  /* +0xe50 */
    rShort ab;  /* +0xe54 */
    rShort lastSample;  /* +0xe58 */
    rShort lastnSampL;  /* +0xe5c */
    rShort lastnSampR;  /* +0xe60 */
    voiceData *IntervalVoices;  /* +0xe64 */
    voiceData vd;  /* +0xe68 */
    int16_t Is16BitSound;  /* +0xfb8 */
    rShort speechVolume;  /* +0xfbc */
    float trackLevel;  /* +0xfc0 */
    float volumeCmd;  /* +0xfc4 */
    int16_t *GMVoiceMap;  /* +0xfc8 */
    voiceDataPtr *GMVoiceData;  /* +0xfcc */
    rShort lastBreath;  /* +0xfd0 */
    int32_t *phonFlags2;  /* +0xfd4 */
    int16_t *logToLinPtr;  /* +0xfd8 */
    int16_t *logOf2Tbl;  /* +0xfdc */
    unsigned char *SineWavePtr;  /* +0xfe0 */
    uint16_t *ExpOf2Tbl;  /* +0xfe4 */
    uint16_t *OctFreqTbl;  /* +0xfe8 */
    int16_t *phon_Buf;  /* +0xfec */
    int16_t *phon_Ctrl_Buf;  /* +0xff0 */
    int16_t *dur_Buf1;  /* +0xff4 */
    int16_t *dur_Buf;  /* +0xff8 */
    int16_t numOfPhons;  /* +0xffc */
    int16_t noteKey;  /* +0xffe */
    int16_t noteVel;  /* +0x1000 */
    float noteDur;  /* +0x1004 */
    int16_t newNote;  /* +0x1008 */
    int16_t nextNote;  /* +0x100a */
    int16_t firstNote;  /* +0x100c */
    int16_t cur_PhonBuf_Index_CF;  /* +0x100e */
    int16_t dur_Done_in_Phon_CF;  /* +0x1010 */
    int16_t cur_Phon_CF;  /* +0x1012 */
    int16_t cur_Phon_Dur_CF;  /* +0x1014 */
    int16_t cur_PhonCtrl_CF;  /* +0x1016 */
    int32_t cur_PhonFlags_CF;  /* +0x1018 */
    int16_t next_Phon_CF;  /* +0x101c */
    int16_t next_PhonCtrl_CF;  /* +0x101e */
    int32_t next_PhonFlags_CF;  /* +0x1020 */
    int16_t prev_Phon_CF;  /* +0x1024 */
    int32_t prev_PhonFlags_CF;  /* +0x1028 */
    int16_t prev_PhonCtrl_CF;  /* +0x102c */
    int16_t prev2_Phon_CF;  /* +0x102e */
    int16_t prev2_PhonCtrl_CF;  /* +0x1030 */
    float VP_baselinePitch;  /* +0x1034 */
    int16_t controlF0;  /* +0x1038 */
    Fixed vibrato_Phase1;  /* +0x103c */
    Fixed vibrato_Phase2;  /* +0x1040 */
    int32_t vibratoDepth1;  /* +0x1044 */
    int32_t vibratoDepth2;  /* +0x1048 */
    int32_t vibratoFreq;  /* +0x104c */
    int16_t speakState;  /* +0x1050 */
    int16_t starting_New_Phon;  /* +0x1052 */
    int16_t tempo;  /* +0x1054 */
    int32_t frameMarker;  /* +0x1058 */
    int16_t voiceVers;  /* +0x105c */
    int16_t songIndex;  /* +0x105e */
    float portamento;  /* +0x1060 */
    float portamentoStep;  /* +0x1064 */
    float portamentoAccum;  /* +0x1068 */
    float portamentoScale;  /* +0x106c */
    int16_t *Time_Tbl;  /* +0x1070 */
    int16_t newPortaTarget;  /* +0x1074 */
    void *musicVars;  /* +0x1078 */
    int16_t speechIsActive;  /* +0x107c */
    int32_t waveIndex;  /* +0x1080 */
    void *musicGlobals;  /* +0x1084 */
    int16_t voiceRef;  /* +0x1088 */
    int32_t zeroCntr;  /* +0x108c */
    int16_t voiceDetune;  /* +0x1090 */
    int16_t singEnabled;  /* +0x1092 */
    int16_t newMidiNote[8];  /* +0x1094 */
    int16_t newMidiVel[8];  /* +0x10a4 */
    int16_t midiNoteCount;  /* +0x10b4 */
    int16_t midiNoteIN;  /* +0x10b6 */
    int16_t midiNoteOUT;  /* +0x10b8 */
    int16_t freezeFrame;  /* +0x10ba */
    rShort waveAmp1;  /* +0x10bc */
    rShort waveAmp2;  /* +0x10c0 */
    rShort curVel;  /* +0x10c4 */
    int32_t susTime;  /* +0x10c8 */
    int32_t pitchBend;  /* +0x10cc */
    int32_t PB_Range;  /* +0x10d0 */
    int16_t MIDIMode;  /* +0x10d4 */
    int16_t s_oscConfigA;  /* +0x10d6 */
    int16_t *s_waveAddrA;  /* +0x10d8 */
    int32_t s_waveSizeA;  /* +0x10dc */
    float s_waveVolA;  /* +0x10e0 */
    int32_t s_pitchA;  /* +0x10e4 */
    int16_t s_oscConfigB;  /* +0x10e8 */
    int16_t *s_waveAddrB;  /* +0x10ec */
    int32_t s_waveSizeB;  /* +0x10f0 */
    float s_waveVolB;  /* +0x10f4 */
    int32_t s_pitchB;  /* +0x10f8 */
    uint32_t sGlottAccumulator;  /* +0x10fc */
    int16_t sGlottState;  /* +0x1100 */
    int16_t sGlottInSwap;  /* +0x1102 */
    int32_t sGlottPhaseIncA;  /* +0x1104 */
    int32_t sGlottWaveLenA;  /* +0x1108 */
    int16_t *sGlottWaveAddrA;  /* +0x110c */
    float sGlottVolumeA;  /* +0x1110 */
    int16_t sGlottModeA;  /* +0x1114 */
    int16_t sGlottDirA;  /* +0x1116 */
    int32_t sGlottPhaseIncB;  /* +0x1118 */
    int32_t sGlottWaveLenB;  /* +0x111c */
    int16_t *sGlottWaveAddrB;  /* +0x1120 */
    float sGlottVolumeB;  /* +0x1124 */
    int16_t sGlottModeB;  /* +0x1128 */
};

struct VCB_Gen {  /* 40 bytes in the original */
    int16_t Detune;  /* +0x0 */
    int16_t volA;  /* +0x2 */
    int16_t volB;  /* +0x4 */
    int16_t vfreqA;  /* +0x6 */
    int16_t vfreqB;  /* +0x8 */
    int32_t vibratoFreq;  /* +0xc */
    int32_t vibratoDepth;  /* +0x10 */
    int32_t vibrato_Phase;  /* +0x14 */
    int16_t vibrato;  /* +0x18 */
    uint16_t vibratoDelay;  /* +0x1a */
    uint16_t vibratoRamp;  /* +0x1c */
    int32_t vibrato_Accum;  /* +0x20 */
    int16_t vibrato_State;  /* +0x24 */
};

struct VoiceCtrlBlock {  /* 152 bytes in the original */
    int16_t vcbCH;  /* +0x0 */
    int16_t genNum;  /* +0x2 */
    int32_t PBgain;  /* +0x4 */
    int16_t sus_hold;  /* +0x8 */
    int16_t sus_flag;  /* +0xa */
    int16_t envState;  /* +0xc */
    int16_t priority;  /* +0xe */
    int16_t note;  /* +0x10 */
    int16_t chan;  /* +0x12 */
    int16_t segState;  /* +0x14 */
    uint16_t decayStep;  /* +0x16 */
    uint16_t sustainLevel;  /* +0x18 */
    uint16_t releaseStep;  /* +0x1a */
    int32_t env_lim;  /* +0x1c */
    int32_t env_inc;  /* +0x20 */
    int32_t env_cur;  /* +0x24 */
    int32_t env_dir;  /* +0x28 */
    int16_t addDky;  /* +0x2c */
    int32_t stepInitial;  /* +0x30 */
    int32_t stepAccel;  /* +0x34 */
    int32_t atkAccelGain;  /* +0x38 */
    int32_t dkyAccelGain;  /* +0x3c */
    int16_t atkSlope;  /* +0x40 */
    mFloat noteDur;  /* +0x44 */
    VCB_Gen genParams[2];  /* +0x48 */
};

struct DOC_Regs {  /* 48 bytes in the original */
    int32_t accumulator;  /* +0x0 */
    int16_t state;  /* +0x4 */
    int16_t inSwap;  /* +0x6 */
    int16_t modeA;  /* +0x8 */
    int16_t dirA;  /* +0xa */
    int32_t phaseIncA;  /* +0xc */
    int32_t waveLenA;  /* +0x10 */
    signed char *waveAddrA;  /* +0x14 */
    int16_t volumeA;  /* +0x18 */
    int16_t modeB;  /* +0x1a */
    int16_t dirB;  /* +0x1c */
    int32_t phaseIncB;  /* +0x20 */
    int32_t waveLenB;  /* +0x24 */
    signed char *waveAddrB;  /* +0x28 */
    int16_t volumeB;  /* +0x2c */
};

struct MIDI_Item {  /* 20 bytes in the original */
    int16_t cmd;  /* +0x0 */
    int16_t key;  /* +0x2 */
    int16_t vol;  /* +0x4 */
    int16_t chan;  /* +0x6 */
    int16_t track;  /* +0x8 */
    mFloat dur;  /* +0xc */
    int16_t nextKey;  /* +0x10 */
    uint16_t vocalIndex;  /* +0x12 */
};

struct REVERBMOD {  /* 24 bytes in the original */
    float m_lGain;  /* +0x0 */
    int32_t m_dwDelayBufferSize;  /* +0x4 */
    float *m_psDelayBuffer;  /* +0x8 */
    float *m_psDelayIn;  /* +0xc */
    float *m_psDelayOut;  /* +0x10 */
    float *m_psDelayEnd;  /* +0x14 */
};

struct MIDI_Dur_Type {  /* 8 bytes in the original */
    int16_t note;  /* +0x0 */
    int16_t channel;  /* +0x2 */
    mFloat duration;  /* +0x4 */
};

struct WaveList {  /* 40 bytes in the original */
    int16_t topKey;  /* +0x0 */
    int16_t detune;  /* +0x2 */
    int32_t delay;  /* +0x4 */
    int16_t oscConfigA;  /* +0x8 */
    signed char *waveAddrA;  /* +0xc */
    int32_t waveSizeA;  /* +0x10 */
    int16_t volA;  /* +0x14 */
    int16_t pitchA;  /* +0x16 */
    int16_t oscConfigB;  /* +0x18 */
    signed char *waveAddrB;  /* +0x1c */
    int32_t waveSizeB;  /* +0x20 */
    int16_t volB;  /* +0x24 */
    int16_t pitchB;  /* +0x26 */
};

struct OCB {  /* 1344 bytes in the original */
    WaveList waveList_OCB[2][16];  /* +0x0 */
    int16_t atkRate;  /* +0x500 */
    int32_t atkVS;  /* +0x504 */
    uint16_t dkyStep;  /* +0x508 */
    uint16_t susBkpt;  /* +0x50a */
    uint16_t relStep;  /* +0x50c */
    int16_t WLNum_OCB;  /* +0x50e */
    int16_t VGainScale_OCB;  /* +0x510 */
    int16_t VGainAdd_OCB;  /* +0x512 */
    int32_t pitchBend_OCB;  /* +0x514 */
    int32_t decayKbd_OCB;  /* +0x518 */
    int32_t atkAccelGain;  /* +0x51c */
    int32_t dkyAccelGain;  /* +0x520 */
    int16_t atkSlope;  /* +0x524 */
    int32_t vibratoFreq[2];  /* +0x528 */
    int32_t vibratoDepth[2];  /* +0x530 */
    uint16_t vibratoDelay[2];  /* +0x538 */
    uint16_t vibratoRamp[2];  /* +0x53c */
};

struct synthVars {  /* 200836 bytes in the original */
    uint32_t ret;  /* +0x0 */
    Ptr shellV;  /* +0x4 */
    int16_t bit16_Sound;  /* +0x8 */
    int16_t Busy;  /* +0xa */
    int16_t curSndFrame;  /* +0xc */
    VoiceCtrlBlock VCB_Array[48];  /* +0x10 */
    DOC_Regs doc[96];  /* +0x1c90 */
    int32_t *Freq_Tbl;  /* +0x2e90 */
    int16_t *Note_Tbl_Def;  /* +0x2e94 */
    int16_t *NoteDecayTbl;  /* +0x2e98 */
    int16_t *Time_Tbl;  /* +0x2e9c */
    int16_t *VG_Scale;  /* +0x2ea0 */
    int16_t *VG_Add;  /* +0x2ea4 */
    int16_t *OscModeTbl;  /* +0x2ea8 */
    int16_t *InitialOscState;  /* +0x2eac */
    int16_t *Oct_Tbl;  /* +0x2eb0 */
    unsigned char *SineWavePtr;  /* +0x2eb4 */
    int16_t *velToLinPtr;  /* +0x2eb8 */
    int16_t *GM_Map;  /* +0x2ebc */
    int16_t *GM_DrumMap;  /* +0x2ec0 */
    int32_t *SpeechTbls;  /* +0x2ec4 */
    void *speechVars[20];  /* +0x2ec8 */
    int16_t speechChanToTrack[20];  /* +0x2f18 */
    int32_t startNoteNum[20];  /* +0x2f40 */
    Ptr GMVoicePtr;  /* +0x2f90 */
    int16_t *sampleBuffer;  /* +0x2f94 */
    int16_t nextSampBuf;  /* +0x2f98 */
    int16_t *sampleBuffer1;  /* +0x2f9c */
    int16_t *sampleBuffer2;  /* +0x2fa0 */
    int32_t waveIndex;  /* +0x2fa4 */
    int16_t chanToOCB[34];  /* +0x2fa8 */
    int16_t chVolTbl[34];  /* +0x2fec */
    int16_t chSusTbl[34];  /* +0x3030 */
    int32_t chPBTbl[34];  /* +0x3074 */
    int32_t chPBRange[34];  /* +0x30fc */
    int16_t chanPitch[34];  /* +0x3184 */
    int32_t chDetune[34];  /* +0x31c8 */
    uint16_t freeRunTimer;  /* +0x3250 */
    int16_t clockSource;  /* +0x3252 */
    uint16_t seqFlags;  /* +0x3254 */
    int16_t tempoBPM;  /* +0x3256 */
    uint32_t tempo;  /* +0x3258 */
    uint32_t meter;  /* +0x325c */
    uint32_t beatTicks;  /* +0x3260 */
    mFloat timer;  /* +0x3264 */
    mFloat timeWarp;  /* +0x3268 */
    mFloat timeWarp_P;  /* +0x326c */
    mFloat timeWarp_Inv;  /* +0x3270 */
    mFloat tempoMul;  /* +0x3274 */
    int16_t countDown;  /* +0x3278 */
    MIDI_Item itemQueue[128];  /* +0x327c */
    int16_t queueOUT;  /* +0x3c7c */
    int16_t queueIN;  /* +0x3c7e */
    int16_t Vchan;  /* +0x3c80 */
    int16_t Vkey;  /* +0x3c82 */
    int16_t Vtrack;  /* +0x3c84 */
    int16_t Vvol;  /* +0x3c86 */
    int16_t Vocb;  /* +0x3c88 */
    mFloat Vdur;  /* +0x3c8c */
    MIDI_Item foreQueue[32];  /* +0x3c90 */
    int16_t foreQueueOUT;  /* +0x3f10 */
    int16_t foreQueueIN;  /* +0x3f12 */
    int16_t noteList[4352];  /* +0x3f14 */
    WaveDefPtr Wave_Data;  /* +0x6114 */
    int16_t PCMType;  /* +0x6118 */
    int16_t sysVolume;  /* +0x611a */
    int32_t lastnSamp_L;  /* +0x611c */
    int32_t lastnSamp_R;  /* +0x6120 */
    int32_t maxSamp;  /* +0x6124 */
    int32_t minSamp;  /* +0x6128 */
    uint32_t sampleMixer[220];  /* +0x612c */
    int16_t doPostSeq;  /* +0x649c */
    int16_t songHasSpeech;  /* +0x649e */
    SeqInfoPtr seqInfo;  /* +0x64a0 */
    int16_t NumOfSpeechChans;  /* +0x64a4 */
    uint32_t seqStatus;  /* +0x64a8 */
    int16_t PlayTrackMap[32];  /* +0x64ac */
    unsigned char *seqPlayBuf[32];  /* +0x64ec */
    int32_t SpeechMap[32];  /* +0x656c */
    int32_t TrackFlagBits[34];  /* +0x65ec */
    int16_t TrackLevel[34];  /* +0x6674 */
    int16_t polyphony;  /* +0x66b8 */
    mFloat ticksPerBeat;  /* +0x66bc */
    mFloat beatCount;  /* +0x66c0 */
    int16_t karaokeTrack;  /* +0x66c4 */
    mFloat *CosTbl;  /* +0x66c8 */
    mFloat *BcoeffTbl;  /* +0x66cc */
    mFloat *CcoeffTbl;  /* +0x66d0 */
    mFloat delay1L;  /* +0x66d4 */
    mFloat delay1R;  /* +0x66d8 */
    mFloat delay2L;  /* +0x66dc */
    mFloat delay2R;  /* +0x66e0 */
    int16_t filterPitch;  /* +0x66e4 */
    int16_t filterBW;  /* +0x66e6 */
    float m_dwWetVol_h;  /* +0x66e8 */
    float m_dwDryVol_h;  /* +0x66ec */
    REVERBMOD m_LEFT_Mods_h[4];  /* +0x66f0 */
    REVERBMOD m_RIGHT_Mods_h[4];  /* +0x6750 */
    int16_t stereo_Synth_ON_h;  /* +0x67b0 */
    int16_t newReverb_h;  /* +0x67b2 */
    uint32_t roomDelay;  /* +0x67b4 */
    float reverbOutGain;  /* +0x67b8 */
    int16_t reverbON;  /* +0x67bc */
    int32_t m_dwWorkBufferSize;  /* +0x67c0 */
    float *m_psLeft;  /* +0x67c4 */
    float *m_psRight;  /* +0x67c8 */
    float *m_psDryLeft;  /* +0x67cc */
    float *m_psDryRight;  /* +0x67d0 */
    float m_dwWetVol;  /* +0x67d4 */
    float m_dwDryVol;  /* +0x67d8 */
    REVERBMOD m_LEFT_Mods[4];  /* +0x67dc */
    REVERBMOD m_RIGHT_Mods[4];  /* +0x683c */
    int16_t stereo_Synth_ON;  /* +0x689c */
    int32_t srcLen;  /* +0x68a0 */
    int32_t destLen;  /* +0x68a4 */
    unsigned char *inSeq;  /* +0x68a8 */
    unsigned char *outSeq;  /* +0x68ac */
    int32_t outSeqIndex;  /* +0x68b0 */
    int16_t format;  /* +0x68b4 */
    int16_t ntrks;  /* +0x68b6 */
    int16_t division;  /* +0x68b8 */
    char MsgBuff[266];  /* +0x68ba */
    int32_t midi_tempo;  /* +0x69c4 */
    int16_t gotTempo;  /* +0x69c8 */
    int16_t gotTimeSig;  /* +0x69ca */
    int16_t trackNum;  /* +0x69cc */
    int16_t trackType[32];  /* +0x69ce */
    int16_t trackStatus[32];  /* +0x6a0e */
    int32_t trackIndex[32];  /* +0x6a50 */
    int32_t trackName[32];  /* +0x6ad0 */
    int16_t trackPgmChange[32];  /* +0x6b50 */
    int16_t trackFlags[32];  /* +0x6b90 */
    int32_t usedChans[32];  /* +0x6bd0 */
    int32_t noteChanBits;  /* +0x6c50 */
    int32_t SMFCopyright;  /* +0x6c54 */
    int16_t usedTracks;  /* +0x6c58 */
    int16_t beatsPerMeasure;  /* +0x6c5a */
    int16_t beatTo;  /* +0x6c5c */
    int32_t accumTime_I;  /* +0x6c60 */
    mFloat accumTime;  /* +0x6c64 */
    mFloat timeScale;  /* +0x6c68 */
    mFloat tempoScale;  /* +0x6c6c */
    int32_t maxSampleL;  /* +0x6c70 */
    int32_t maxSampleR;  /* +0x6c74 */
    char *metaNameStr;  /* +0x6c78 */
    char *trackNameStr;  /* +0x6c7c */
    int16_t *MidiLengths;  /* +0x6c80 */
    int16_t trackhasMeta;  /* +0x6c84 */
    int16_t noMoreTempo;  /* +0x6c86 */
    int16_t noMoreSig;  /* +0x6c88 */
    int16_t usedPgms[128];  /* +0x6c8a */
    int16_t chanFilter;  /* +0x6d8a */
    int16_t regParam;  /* +0x6d8c */
    int16_t maxTempo;  /* +0x6d8e */
    int16_t minTempo;  /* +0x6d90 */
    int16_t lyricsAllowed;  /* +0x6d92 */
    int16_t phonsAllowed;  /* +0x6d94 */
    int16_t hasKaraText;  /* +0x6d96 */
    int32_t karaTextCount;  /* +0x6d98 */
    int16_t makeTextCB;  /* +0x6d9c */
    _i_CvtSMFProg_Ptr convert_InfoCB;  /* +0x6da0 */
    int32_t convert_RefCon;  /* +0x6da4 */
    mFloat lastMIDI_Vol;  /* +0x6da8 */
    mFloat lastMIDI_Express;  /* +0x6dac */
    uint16_t *Opcode_To_ASCII;  /* +0x6db0 */
    int16_t *phonTypeTbl;  /* +0x6db4 */
    int32_t *phonFlags2;  /* +0x6db8 */
    int16_t *maxDurTbl;  /* +0x6dbc */
    int16_t *minDurTbl;  /* +0x6dc0 */
    int16_t *hash;  /* +0x6dc4 */
    unsigned char *rule;  /* +0x6dc8 */
    unsigned char *kind;  /* +0x6dcc */
    unsigned char *dashruletab;  /* +0x6dd0 */
    unsigned char *atruletab;  /* +0x6dd4 */
    unsigned char *lruletab;  /* +0x6dd8 */
    unsigned char *mruletab;  /* +0x6ddc */
    unsigned char *zruletab;  /* +0x6de0 */
    unsigned char *percentruletab;  /* +0x6de4 */
    unsigned char *bruletab;  /* +0x6de8 */
    unsigned char *SuffixTab;  /* +0x6dec */
    int16_t *SuffixType;  /* +0x6df0 */
    int16_t e_direction;  /* +0x6df4 */
    int16_t dictFile;  /* +0x6df6 */
    uint16_t *srcParseBuf;  /* +0x6df8 */
    int32_t srcParseLen;  /* +0x6dfc */
    int32_t destParseLen;  /* +0x6e00 */
    int16_t *phon_Buf_1;  /* +0x6e04 */
    int16_t *phon_Ctrl_Buf_1;  /* +0x6e08 */
    int16_t phonBuf_1_In_Index;  /* +0x6e0c */
    int16_t *phon_Buf_2;  /* +0x6e10 */
    int16_t *phon_Ctrl_Buf_2;  /* +0x6e14 */
    int16_t *dur_Buf;  /* +0x6e18 */
    int16_t phonBuf_1_Out_Index;  /* +0x6e1c */
    int16_t phonBuf_2_In_Index;  /* +0x6e1e */
    int16_t speech_Rate;  /* +0x6e20 */
    int32_t rate_Ratio;  /* +0x6e24 */
    int32_t rate_Ratio_LowGain;  /* +0x6e28 */
    MIDI_Dur_Type MIDI_Dur_List[64];  /* +0x6e2c */
    int16_t trackToMIDI[34];  /* +0x702c */
    OCB OCB_Array[128];  /* +0x7070 */
    int16_t metro;  /* +0x31070 */
    int16_t playMerto;  /* +0x31072 */
    unsigned char *rec_BufPtr;  /* +0x31074 */
    unsigned char *rec_BufPtr_End;  /* +0x31078 */
    int32_t SoundBufferFrames;  /* +0x3107c */
    uint32_t SoundBufferLen;  /* +0x31080 */
};

struct Float80 {  /* 10 bytes in the original */
    SInt16 exp;  /* +0x0 */
    UInt16 man[4];  /* +0x2 */
};

struct ExtSoundHeader {  /* 66 bytes in the original */
    Ptr samplePtr;  /* +0x0 */
    uint32_t numChannels;  /* +0x4 */
    UnsignedFixed sampleRate;  /* +0x8 */
    uint32_t loopStart;  /* +0xc */
    uint32_t loopEnd;  /* +0x10 */
    UInt8 encode;  /* +0x14 */
    UInt8 baseFrequency;  /* +0x15 */
    uint32_t numFrames;  /* +0x16 */
    extended80 AIFFSampleRate;  /* +0x1a */
    Ptr markerChunk;  /* +0x24 */
    Ptr instrumentChunks;  /* +0x28 */
    Ptr AESRecording;  /* +0x2c */
    uint16_t sampleSize;  /* +0x30 */
    uint16_t futureUse1;  /* +0x32 */
    uint32_t futureUse2;  /* +0x34 */
    uint32_t futureUse3;  /* +0x38 */
    uint32_t futureUse4;  /* +0x3c */
    UInt8 sampleArea[1];  /* +0x40 */
};

struct SndCommand {  /* 8 bytes in the original */
    uint16_t cmd;  /* +0x0 */
    int16_t param1;  /* +0x2 */
    int32_t param2;  /* +0x4 */
};

struct DeferredTask {  /* 20 bytes in the original */
    volatile QElemPtr qLink;  /* +0x0 */
    int16_t qType;  /* +0x4 */
    volatile int16_t dtFlags;  /* +0x6 */
    DeferredTaskUPP dtAddr;  /* +0x8 */
    int32_t dtParam;  /* +0xc */
    int32_t dtReserved;  /* +0x10 */
};

struct UnsignedWide {  /* 8 bytes in the original */
    UInt32 hi;  /* +0x0 */
    UInt32 lo;  /* +0x4 */
};

struct TMTask {  /* 22 bytes in the original */
    QElemPtr qLink;  /* +0x0 */
    int16_t qType;  /* +0x4 */
    TimerUPP tmAddr;  /* +0x6 */
    int32_t tmCount;  /* +0xa */
    int32_t tmWakeUp;  /* +0xe */
    int32_t tmReserved;  /* +0x12 */
};

struct TMinfo {  /* 36 bytes in the original */
    TMTask TimeMgrTask;  /* +0x0 */
    int16_t inUse;  /* +0x16 */
    Ptr refCon;  /* +0x18 */
    uint32_t data;  /* +0x1c */
    uint32_t count;  /* +0x20 */
};

struct shellVar {  /* 668 bytes in the original */
    uint32_t ret;  /* +0x0 */
    SndChannelPtr SndChan;  /* +0x4 */
    Ptr nullBufPtr;  /* +0x8 */
    Ptr soundBufPtr;  /* +0xc */
    ExtSoundHeader SH;  /* +0x10 */
    SndCommand SCmd;  /* +0x52 */
    uint32_t CallerA5;  /* +0x5c */
    int16_t inMusicDT;  /* +0x60 */
    DeferredTaskUPP MusicDTProc;  /* +0x64 */
    SndCallBackUPP SoundCBProc;  /* +0x68 */
    int16_t doAnotherBuffer;  /* +0x6c */
    DeferredTask DT;  /* +0x6e */
    int16_t lastSndBuffer;  /* +0x82 */
    int16_t doneWithMusic;  /* +0x84 */
    int16_t *curSampleBuffer;  /* +0x88 */
    int32_t curSampleLen;  /* +0x8c */
    int16_t *firstSampleBuffer;  /* +0x90 */
    int32_t firstSampleLen;  /* +0x94 */
    int16_t firstBuffer;  /* +0x98 */
    char *MemBufStart;  /* +0x9c */
    char *MemBufEnd;  /* +0xa0 */
    int32_t latencyMS;  /* +0xa4 */
    synthVarsPtr ChannelGlobals;  /* +0xa8 */
    SeqErrorUPP seqErrorCallBackProc;  /* +0xac */
    SeqItemUPP seqItemCallBackProc;  /* +0xb0 */
    SeqMarkUPP seqMarkCallBackProc;  /* +0xb4 */
    TimerUPP seqItem_CBTimerProc;  /* +0xb8 */
    TimerUPP seqMark_CBTimerProc;  /* +0xbc */
    TempoUPP tempoCallBackProc;  /* +0xc0 */
    TimerUPP tempo_CBTimerProc;  /* +0xc4 */
    int32_t tempoRefCon;  /* +0xc8 */
    BeatUPP beatCallBackProc;  /* +0xcc */
    TimerUPP beat_CBTimerProc;  /* +0xd0 */
    int32_t beatRefCon;  /* +0xd4 */
    SeqDoneUPP seqDoneCallBackProc;  /* +0xd8 */
    int32_t seqDoneRefCon;  /* +0xdc */
    MeterUPP meterCallBackProc;  /* +0xe0 */
    int32_t meterRefCon;  /* +0xe4 */
    OverloadUPP OverloadCallBackProc;  /* +0xe8 */
    int32_t OverloadRefCon;  /* +0xec */
    KaraUPP karaCallBackProc;  /* +0xf0 */
    TimerUPP kara_CBTimerProc;  /* +0xf4 */
    int32_t karaRefCon;  /* +0xf8 */
    uint32_t userA5;  /* +0xfc */
    uint32_t userRefCon;  /* +0x100 */
    int16_t stopMusic;  /* +0x104 */
    int16_t soundCB_Count;  /* +0x106 */
    UnsignedWide timeZero;  /* +0x108 */
    uint32_t timeAccum;  /* +0x110 */
    TMinfo timeTasks[8];  /* +0x114 */
    int16_t nextTask;  /* +0x234 */
    TMinfoPtr freeTask;  /* +0x238 */
    int16_t timerPending;  /* +0x23c */
    int32_t SoundBufferFrames;  /* +0x240 */
    uint32_t SoundBufferTime;  /* +0x244 */
    uint32_t SoundBufferLen;  /* +0x248 */
    int16_t cb_Count;  /* +0x24c */
    int32_t curMaxL;  /* +0x250 */
    int32_t curMaxR;  /* +0x254 */
    int32_t nextMaxL;  /* +0x258 */
    int32_t nextMaxR;  /* +0x25c */
    uint32_t backTime1;  /* +0x260 */
    uint32_t backTime2;  /* +0x264 */
    uint32_t backTime;  /* +0x268 */
    uint32_t frameTime1;  /* +0x26c */
    uint32_t frameTime2;  /* +0x270 */
    uint32_t frameTime;  /* +0x274 */
    Ptr MIDI_Out_Buffer;  /* +0x278 */
    int32_t MIDI_Out_Index;  /* +0x27c */
    Ptr MIDI_Buf1;  /* +0x280 */
    Ptr MIDI_Buf2;  /* +0x284 */
    int32_t MIDI_Index1;  /* +0x288 */
    int32_t MIDI_Index2;  /* +0x28c */
    int32_t MIDI_BufSel;  /* +0x290 */
    OMSOutUPP OMSOutCallBackProc;  /* +0x294 */
    int16_t reverbEnabled;  /* +0x298 */
};

struct REVERBCONFIG {  /* 72 bytes in the original */
    float m_fltDBWet;  /* +0x0 */
    float m_fltDBDry;  /* +0x4 */
    float m_pfltLeftDelay[4];  /* +0x8 */
    float m_pfltDBLeft[4];  /* +0x18 */
    float m_pfltRightDelay[4];  /* +0x28 */
    float m_pfltDBRight[4];  /* +0x38 */
};

struct PhonSyllableRec {  /* 12 bytes in the original */
    unsigned char syllStr[8];  /* +0x0 */
    int32_t syllLen;  /* +0x8 */
};

struct ConvertTextRec {  /* 272 bytes in the original */
    unsigned char text_Input[16];  /* +0x0 */
    int32_t textLen_Input;  /* +0x10 */
    int32_t syllables_Result;  /* +0x14 */
    PhonSyllableRec phon_Result[10];  /* +0x18 */
    int32_t hasAlt_Result;  /* +0x90 */
    int32_t alt_Syllables_Result;  /* +0x94 */
    PhonSyllableRec alt_Phon_Result[10];  /* +0x98 */
};

struct FEToken {  /* 180 bytes in the original */
    unsigned char tokStr[37];  /* +0x0 */
    int16_t tokLen;  /* +0x26 */
    unsigned char phonStr[61];  /* +0x28 */
    unsigned char phonHold[61];  /* +0x65 */
    uint32_t bufOffset;  /* +0xa4 */
    int16_t inDict;  /* +0xa8 */
    int16_t inMorph;  /* +0xaa */
    int16_t hasAlt;  /* +0xac */
    int16_t altChoice;  /* +0xae */
    int16_t suffix;  /* +0xb0 */
    uint16_t addFlags;  /* +0xb2 */
};

struct MIDI_Event {  /* 28 bytes in the original */
    unsigned char *targetTrack;  /* +0x0 */
    uint32_t target_time;  /* +0x4 */
    uint16_t target_chan;  /* +0x8 */
    uint16_t target_cmd;  /* +0xa */
    uint16_t target_key;  /* +0xc */
    uint16_t target_vol;  /* +0xe */
    uint32_t target_dur;  /* +0x10 */
    uint32_t target_endTime;  /* +0x14 */
    uint16_t target_vocals;  /* +0x18 */
};

struct Dict {  /* 140 bytes in the original */
    struct Dict *nextDict;  /* +0x0 */
    uint32_t version;  /* +0x4 */
    uint32_t type;  /* +0x8 */
    uint32_t wordCount;  /* +0xc */
    uint32_t hash[27];  /* +0x10 */
    unsigned char *words;  /* +0x7c */
    IndexEntry *index;  /* +0x80 */
    uint32_t flags;  /* +0x84 */
    uint32_t data[1];  /* +0x88 */
};

struct WaveDef {  /* 24 bytes in the original */
    char waveName[16];  /* +0x0 */
    int32_t waveOffset;  /* +0x10 */
    int32_t waveLen;  /* +0x14 */
};

struct TrackInfo {  /* 88 bytes in the original */
    int32_t trackNum;  /* +0x0 */
    int32_t flags;  /* +0x4 */
    int32_t trackData;  /* +0x8 */
    int32_t trackDataLen;  /* +0xc */
    int32_t speechData;  /* +0x10 */
    int32_t speechDataLen;  /* +0x14 */
    int32_t lyricData;  /* +0x18 */
    int32_t lyricEvents;  /* +0x1c */
    int32_t lyricWidth;  /* +0x20 */
    int32_t trackChannels;  /* +0x24 */
    int16_t midiChannel;  /* +0x28 */
    int16_t unused1;  /* +0x2a */
    int32_t unused2;  /* +0x2c */
    int32_t unused3;  /* +0x30 */
    int32_t unused4;  /* +0x34 */
    char trackName[32];  /* +0x38 */
};

struct SeqInfo {  /* 2816 bytes in the original */
    TrackInfo tracks[32];  /* +0x0 */
};

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define VW_LAYOUT_ASSERT(cond, msg) _Static_assert(cond, msg)
#else
#define VW_LAYOUT_ASSERT(cond, msg) typedef char vw_layout_assert_##__LINE__[(cond) ? 1 : -1]
#endif
VW_LAYOUT_ASSERT(sizeof(struct Frame) == 52, "Frame size");
VW_LAYOUT_ASSERT(offsetof(struct Frame, Av) == 0, "Frame.Av");
VW_LAYOUT_ASSERT(offsetof(struct Frame, Af) == 2, "Frame.Af");
VW_LAYOUT_ASSERT(offsetof(struct Frame, f0) == 4, "Frame.f0");
VW_LAYOUT_ASSERT(offsetof(struct Frame, f1) == 6, "Frame.f1");
VW_LAYOUT_ASSERT(offsetof(struct Frame, f2) == 8, "Frame.f2");
VW_LAYOUT_ASSERT(offsetof(struct Frame, f3) == 10, "Frame.f3");
VW_LAYOUT_ASSERT(offsetof(struct Frame, a2) == 12, "Frame.a2");
VW_LAYOUT_ASSERT(offsetof(struct Frame, a3) == 14, "Frame.a3");
VW_LAYOUT_ASSERT(offsetof(struct Frame, a4) == 16, "Frame.a4");
VW_LAYOUT_ASSERT(offsetof(struct Frame, a5) == 18, "Frame.a5");
VW_LAYOUT_ASSERT(offsetof(struct Frame, a6) == 20, "Frame.a6");
VW_LAYOUT_ASSERT(offsetof(struct Frame, FNZ) == 22, "Frame.FNZ");
VW_LAYOUT_ASSERT(offsetof(struct Frame, AB) == 24, "Frame.AB");
VW_LAYOUT_ASSERT(offsetof(struct Frame, bw1) == 26, "Frame.bw1");
VW_LAYOUT_ASSERT(offsetof(struct Frame, bw2) == 28, "Frame.bw2");
VW_LAYOUT_ASSERT(offsetof(struct Frame, bw3) == 30, "Frame.bw3");
VW_LAYOUT_ASSERT(offsetof(struct Frame, phon_Edge) == 32, "Frame.phon_Edge");
VW_LAYOUT_ASSERT(offsetof(struct Frame, marker) == 36, "Frame.marker");
VW_LAYOUT_ASSERT(offsetof(struct Frame, velocity) == 40, "Frame.velocity");
VW_LAYOUT_ASSERT(offsetof(struct Frame, f1Gain) == 44, "Frame.f1Gain");
VW_LAYOUT_ASSERT(offsetof(struct Frame, f2Gain) == 46, "Frame.f2Gain");
VW_LAYOUT_ASSERT(offsetof(struct Frame, f3Gain) == 48, "Frame.f3Gain");
VW_LAYOUT_ASSERT(sizeof(struct voiceData) == 336, "voiceData size");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, voiceName) == 0, "voiceData.voiceName");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, voice) == 16, "voiceData.voice");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, vGain) == 18, "voiceData.vGain");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, aGain) == 20, "voiceData.aGain");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, aCycle) == 22, "voiceData.aCycle");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, f4_Freq) == 24, "voiceData.f4_Freq");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, f4_BW) == 26, "voiceData.f4_BW");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, f5_Freq) == 28, "voiceData.f5_Freq");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, f5_BW) == 30, "voiceData.f5_BW");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, f4p_Freq) == 32, "voiceData.f4p_Freq");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, f4p_BW) == 34, "voiceData.f4p_BW");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, f5p_Freq) == 36, "voiceData.f5p_Freq");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, f5p_BW) == 38, "voiceData.f5p_BW");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, f6p_Freq) == 40, "voiceData.f6p_Freq");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, f6p_BW) == 42, "voiceData.f6p_BW");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, nasal_Base) == 44, "voiceData.nasal_Base");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, nasal_targ) == 46, "voiceData.nasal_targ");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, nasal_BW) == 48, "voiceData.nasal_BW");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, locus) == 50, "voiceData.locus");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, bwGain1) == 52, "voiceData.bwGain1");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, bwGain2) == 54, "voiceData.bwGain2");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, bwGain3) == 56, "voiceData.bwGain3");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, f1_Offset) == 58, "voiceData.f1_Offset");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, f2_Offset) == 60, "voiceData.f2_Offset");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, f3_Offset) == 62, "voiceData.f3_Offset");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, chorus) == 64, "voiceData.chorus");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, nGain) == 66, "voiceData.nGain");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, sPitch) == 68, "voiceData.sPitch");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, sGain) == 70, "voiceData.sGain");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, AsperW) == 72, "voiceData.AsperW");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, waveType) == 74, "voiceData.waveType");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, vWave) == 76, "voiceData.vWave");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, vWave1) == 172, "voiceData.vWave1");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, customForm) == 268, "voiceData.customForm");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, nasalAmt) == 270, "voiceData.nasalAmt");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, emphVoice) == 272, "voiceData.emphVoice");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, rvbDelay) == 274, "voiceData.rvbDelay");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, rvbDepth) == 276, "voiceData.rvbDepth");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, voiceVers) == 278, "voiceData.voiceVers");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, waveRefA) == 280, "voiceData.waveRefA");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, octTuneA) == 282, "voiceData.octTuneA");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, semiTuneA) == 284, "voiceData.semiTuneA");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, fineTuneA) == 286, "voiceData.fineTuneA");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, oscVolA) == 288, "voiceData.oscVolA");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, waveRefB) == 290, "voiceData.waveRefB");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, octTuneB) == 292, "voiceData.octTuneB");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, semiTuneB) == 294, "voiceData.semiTuneB");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, fineTuneB) == 296, "voiceData.fineTuneB");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, oscVolB) == 298, "voiceData.oscVolB");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, oscMode) == 300, "voiceData.oscMode");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, sync) == 302, "voiceData.sync");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, free1) == 304, "voiceData.free1");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, free2) == 308, "voiceData.free2");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, free3) == 312, "voiceData.free3");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, free4) == 316, "voiceData.free4");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, free5) == 320, "voiceData.free5");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, free6) == 324, "voiceData.free6");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, free7) == 328, "voiceData.free7");
VW_LAYOUT_ASSERT(offsetof(struct voiceData, free8) == 332, "voiceData.free8");
VW_LAYOUT_ASSERT(sizeof(struct VCB_Gen) == 40, "VCB_Gen size");
VW_LAYOUT_ASSERT(offsetof(struct VCB_Gen, Detune) == 0, "VCB_Gen.Detune");
VW_LAYOUT_ASSERT(offsetof(struct VCB_Gen, volA) == 2, "VCB_Gen.volA");
VW_LAYOUT_ASSERT(offsetof(struct VCB_Gen, volB) == 4, "VCB_Gen.volB");
VW_LAYOUT_ASSERT(offsetof(struct VCB_Gen, vfreqA) == 6, "VCB_Gen.vfreqA");
VW_LAYOUT_ASSERT(offsetof(struct VCB_Gen, vfreqB) == 8, "VCB_Gen.vfreqB");
VW_LAYOUT_ASSERT(offsetof(struct VCB_Gen, vibratoFreq) == 12, "VCB_Gen.vibratoFreq");
VW_LAYOUT_ASSERT(offsetof(struct VCB_Gen, vibratoDepth) == 16, "VCB_Gen.vibratoDepth");
VW_LAYOUT_ASSERT(offsetof(struct VCB_Gen, vibrato_Phase) == 20, "VCB_Gen.vibrato_Phase");
VW_LAYOUT_ASSERT(offsetof(struct VCB_Gen, vibrato) == 24, "VCB_Gen.vibrato");
VW_LAYOUT_ASSERT(offsetof(struct VCB_Gen, vibratoDelay) == 26, "VCB_Gen.vibratoDelay");
VW_LAYOUT_ASSERT(offsetof(struct VCB_Gen, vibratoRamp) == 28, "VCB_Gen.vibratoRamp");
VW_LAYOUT_ASSERT(offsetof(struct VCB_Gen, vibrato_Accum) == 32, "VCB_Gen.vibrato_Accum");
VW_LAYOUT_ASSERT(offsetof(struct VCB_Gen, vibrato_State) == 36, "VCB_Gen.vibrato_State");
VW_LAYOUT_ASSERT(sizeof(struct VoiceCtrlBlock) == 152, "VoiceCtrlBlock size");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, vcbCH) == 0, "VoiceCtrlBlock.vcbCH");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, genNum) == 2, "VoiceCtrlBlock.genNum");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, PBgain) == 4, "VoiceCtrlBlock.PBgain");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, sus_hold) == 8, "VoiceCtrlBlock.sus_hold");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, sus_flag) == 10, "VoiceCtrlBlock.sus_flag");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, envState) == 12, "VoiceCtrlBlock.envState");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, priority) == 14, "VoiceCtrlBlock.priority");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, note) == 16, "VoiceCtrlBlock.note");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, chan) == 18, "VoiceCtrlBlock.chan");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, segState) == 20, "VoiceCtrlBlock.segState");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, decayStep) == 22, "VoiceCtrlBlock.decayStep");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, sustainLevel) == 24, "VoiceCtrlBlock.sustainLevel");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, releaseStep) == 26, "VoiceCtrlBlock.releaseStep");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, env_lim) == 28, "VoiceCtrlBlock.env_lim");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, env_inc) == 32, "VoiceCtrlBlock.env_inc");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, env_cur) == 36, "VoiceCtrlBlock.env_cur");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, env_dir) == 40, "VoiceCtrlBlock.env_dir");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, addDky) == 44, "VoiceCtrlBlock.addDky");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, stepInitial) == 48, "VoiceCtrlBlock.stepInitial");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, stepAccel) == 52, "VoiceCtrlBlock.stepAccel");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, atkAccelGain) == 56, "VoiceCtrlBlock.atkAccelGain");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, dkyAccelGain) == 60, "VoiceCtrlBlock.dkyAccelGain");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, atkSlope) == 64, "VoiceCtrlBlock.atkSlope");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, noteDur) == 68, "VoiceCtrlBlock.noteDur");
VW_LAYOUT_ASSERT(offsetof(struct VoiceCtrlBlock, genParams) == 72, "VoiceCtrlBlock.genParams");
VW_LAYOUT_ASSERT(sizeof(struct MIDI_Item) == 20, "MIDI_Item size");
VW_LAYOUT_ASSERT(offsetof(struct MIDI_Item, cmd) == 0, "MIDI_Item.cmd");
VW_LAYOUT_ASSERT(offsetof(struct MIDI_Item, key) == 2, "MIDI_Item.key");
VW_LAYOUT_ASSERT(offsetof(struct MIDI_Item, vol) == 4, "MIDI_Item.vol");
VW_LAYOUT_ASSERT(offsetof(struct MIDI_Item, chan) == 6, "MIDI_Item.chan");
VW_LAYOUT_ASSERT(offsetof(struct MIDI_Item, track) == 8, "MIDI_Item.track");
VW_LAYOUT_ASSERT(offsetof(struct MIDI_Item, dur) == 12, "MIDI_Item.dur");
VW_LAYOUT_ASSERT(offsetof(struct MIDI_Item, nextKey) == 16, "MIDI_Item.nextKey");
VW_LAYOUT_ASSERT(offsetof(struct MIDI_Item, vocalIndex) == 18, "MIDI_Item.vocalIndex");
VW_LAYOUT_ASSERT(sizeof(struct MIDI_Dur_Type) == 8, "MIDI_Dur_Type size");
VW_LAYOUT_ASSERT(offsetof(struct MIDI_Dur_Type, note) == 0, "MIDI_Dur_Type.note");
VW_LAYOUT_ASSERT(offsetof(struct MIDI_Dur_Type, channel) == 2, "MIDI_Dur_Type.channel");
VW_LAYOUT_ASSERT(offsetof(struct MIDI_Dur_Type, duration) == 4, "MIDI_Dur_Type.duration");
VW_LAYOUT_ASSERT(sizeof(struct Float80) == 10, "Float80 size");
VW_LAYOUT_ASSERT(offsetof(struct Float80, exp) == 0, "Float80.exp");
VW_LAYOUT_ASSERT(offsetof(struct Float80, man) == 2, "Float80.man");
VW_LAYOUT_ASSERT(sizeof(struct SndCommand) == 8, "SndCommand size");
VW_LAYOUT_ASSERT(offsetof(struct SndCommand, cmd) == 0, "SndCommand.cmd");
VW_LAYOUT_ASSERT(offsetof(struct SndCommand, param1) == 2, "SndCommand.param1");
VW_LAYOUT_ASSERT(offsetof(struct SndCommand, param2) == 4, "SndCommand.param2");
VW_LAYOUT_ASSERT(sizeof(struct UnsignedWide) == 8, "UnsignedWide size");
VW_LAYOUT_ASSERT(offsetof(struct UnsignedWide, hi) == 0, "UnsignedWide.hi");
VW_LAYOUT_ASSERT(offsetof(struct UnsignedWide, lo) == 4, "UnsignedWide.lo");
VW_LAYOUT_ASSERT(sizeof(struct REVERBCONFIG) == 72, "REVERBCONFIG size");
VW_LAYOUT_ASSERT(offsetof(struct REVERBCONFIG, m_fltDBWet) == 0, "REVERBCONFIG.m_fltDBWet");
VW_LAYOUT_ASSERT(offsetof(struct REVERBCONFIG, m_fltDBDry) == 4, "REVERBCONFIG.m_fltDBDry");
VW_LAYOUT_ASSERT(offsetof(struct REVERBCONFIG, m_pfltLeftDelay) == 8, "REVERBCONFIG.m_pfltLeftDelay");
VW_LAYOUT_ASSERT(offsetof(struct REVERBCONFIG, m_pfltDBLeft) == 24, "REVERBCONFIG.m_pfltDBLeft");
VW_LAYOUT_ASSERT(offsetof(struct REVERBCONFIG, m_pfltRightDelay) == 40, "REVERBCONFIG.m_pfltRightDelay");
VW_LAYOUT_ASSERT(offsetof(struct REVERBCONFIG, m_pfltDBRight) == 56, "REVERBCONFIG.m_pfltDBRight");
VW_LAYOUT_ASSERT(sizeof(struct PhonSyllableRec) == 12, "PhonSyllableRec size");
VW_LAYOUT_ASSERT(offsetof(struct PhonSyllableRec, syllStr) == 0, "PhonSyllableRec.syllStr");
VW_LAYOUT_ASSERT(offsetof(struct PhonSyllableRec, syllLen) == 8, "PhonSyllableRec.syllLen");
VW_LAYOUT_ASSERT(sizeof(struct ConvertTextRec) == 272, "ConvertTextRec size");
VW_LAYOUT_ASSERT(offsetof(struct ConvertTextRec, text_Input) == 0, "ConvertTextRec.text_Input");
VW_LAYOUT_ASSERT(offsetof(struct ConvertTextRec, textLen_Input) == 16, "ConvertTextRec.textLen_Input");
VW_LAYOUT_ASSERT(offsetof(struct ConvertTextRec, syllables_Result) == 20, "ConvertTextRec.syllables_Result");
VW_LAYOUT_ASSERT(offsetof(struct ConvertTextRec, phon_Result) == 24, "ConvertTextRec.phon_Result");
VW_LAYOUT_ASSERT(offsetof(struct ConvertTextRec, hasAlt_Result) == 144, "ConvertTextRec.hasAlt_Result");
VW_LAYOUT_ASSERT(offsetof(struct ConvertTextRec, alt_Syllables_Result) == 148, "ConvertTextRec.alt_Syllables_Result");
VW_LAYOUT_ASSERT(offsetof(struct ConvertTextRec, alt_Phon_Result) == 152, "ConvertTextRec.alt_Phon_Result");
VW_LAYOUT_ASSERT(sizeof(struct FEToken) == 180, "FEToken size");
VW_LAYOUT_ASSERT(offsetof(struct FEToken, tokStr) == 0, "FEToken.tokStr");
VW_LAYOUT_ASSERT(offsetof(struct FEToken, tokLen) == 38, "FEToken.tokLen");
VW_LAYOUT_ASSERT(offsetof(struct FEToken, phonStr) == 40, "FEToken.phonStr");
VW_LAYOUT_ASSERT(offsetof(struct FEToken, phonHold) == 101, "FEToken.phonHold");
VW_LAYOUT_ASSERT(offsetof(struct FEToken, bufOffset) == 164, "FEToken.bufOffset");
VW_LAYOUT_ASSERT(offsetof(struct FEToken, inDict) == 168, "FEToken.inDict");
VW_LAYOUT_ASSERT(offsetof(struct FEToken, inMorph) == 170, "FEToken.inMorph");
VW_LAYOUT_ASSERT(offsetof(struct FEToken, hasAlt) == 172, "FEToken.hasAlt");
VW_LAYOUT_ASSERT(offsetof(struct FEToken, altChoice) == 174, "FEToken.altChoice");
VW_LAYOUT_ASSERT(offsetof(struct FEToken, suffix) == 176, "FEToken.suffix");
VW_LAYOUT_ASSERT(offsetof(struct FEToken, addFlags) == 178, "FEToken.addFlags");
VW_LAYOUT_ASSERT(sizeof(struct WaveDef) == 24, "WaveDef size");
VW_LAYOUT_ASSERT(offsetof(struct WaveDef, waveName) == 0, "WaveDef.waveName");
VW_LAYOUT_ASSERT(offsetof(struct WaveDef, waveOffset) == 16, "WaveDef.waveOffset");
VW_LAYOUT_ASSERT(offsetof(struct WaveDef, waveLen) == 20, "WaveDef.waveLen");
VW_LAYOUT_ASSERT(sizeof(struct TrackInfo) == 88, "TrackInfo size");
VW_LAYOUT_ASSERT(offsetof(struct TrackInfo, trackNum) == 0, "TrackInfo.trackNum");
VW_LAYOUT_ASSERT(offsetof(struct TrackInfo, flags) == 4, "TrackInfo.flags");
VW_LAYOUT_ASSERT(offsetof(struct TrackInfo, trackData) == 8, "TrackInfo.trackData");
VW_LAYOUT_ASSERT(offsetof(struct TrackInfo, trackDataLen) == 12, "TrackInfo.trackDataLen");
VW_LAYOUT_ASSERT(offsetof(struct TrackInfo, speechData) == 16, "TrackInfo.speechData");
VW_LAYOUT_ASSERT(offsetof(struct TrackInfo, speechDataLen) == 20, "TrackInfo.speechDataLen");
VW_LAYOUT_ASSERT(offsetof(struct TrackInfo, lyricData) == 24, "TrackInfo.lyricData");
VW_LAYOUT_ASSERT(offsetof(struct TrackInfo, lyricEvents) == 28, "TrackInfo.lyricEvents");
VW_LAYOUT_ASSERT(offsetof(struct TrackInfo, lyricWidth) == 32, "TrackInfo.lyricWidth");
VW_LAYOUT_ASSERT(offsetof(struct TrackInfo, trackChannels) == 36, "TrackInfo.trackChannels");
VW_LAYOUT_ASSERT(offsetof(struct TrackInfo, midiChannel) == 40, "TrackInfo.midiChannel");
VW_LAYOUT_ASSERT(offsetof(struct TrackInfo, unused1) == 42, "TrackInfo.unused1");
VW_LAYOUT_ASSERT(offsetof(struct TrackInfo, unused2) == 44, "TrackInfo.unused2");
VW_LAYOUT_ASSERT(offsetof(struct TrackInfo, unused3) == 48, "TrackInfo.unused3");
VW_LAYOUT_ASSERT(offsetof(struct TrackInfo, unused4) == 52, "TrackInfo.unused4");
VW_LAYOUT_ASSERT(offsetof(struct TrackInfo, trackName) == 56, "TrackInfo.trackName");
VW_LAYOUT_ASSERT(sizeof(struct SeqInfo) == 2816, "SeqInfo size");
VW_LAYOUT_ASSERT(offsetof(struct SeqInfo, tracks) == 0, "SeqInfo.tracks");

#endif /* VW_TYPES_H */
