#!/usr/bin/env python3
"""Produce the text front end -- src/orthtophon.c, src/parsephons.c,
and include/vw_frontend.h -- from the lifter's output.

    python tools/mkfront.py

The only edits to the lifted text are at the file-format boundary: the
pronunciation dictionary is a big-endian file, and the original read its
header straight into a struct. The port reads the same bytes and swaps the
words it uses, so the file stays what it is on any host.
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

ORTH_PROLOGUE = '''/* OrthToPhon.c -- VocalWriter's letter-to-sound front end.
 *
 * A word is looked up in the pronunciation dictionary (EnglishLex, read
 * through the File Manager: SearchDict binary-searches the file itself),
 * failing that decomposed into a stem and a suffix and looked up again
 * (DoMorph), failing that spelled out by the letter-to-sound rules
 * (EngToP, dorule). Lifted from the original's machine code like the rest;
 * see src/speech.c.
 */
#include "vw_engine.h"

/* The dictionary header as it lies in the file: 140 bytes, big-endian.
 * The original declared it with pointers (struct Dict) and read the file
 * straight over it; the port keeps the file's layout and byte order. */
typedef struct {
    uint32_t nextDict, version, type, wordCount;
    uint32_t hash[27];
    uint32_t words, index, flags, data[1];
} vw_DictFile;

'''

PARSE_PROLOGUE = '''/* ParsePhons.c -- VocalWriter's phoneme parser.
 *
 * Turns the syllables attached to a vocal track (MakeSpeechData) or a
 * looked-up word (TunePhons) into the phoneme, control and duration
 * lists the synthesiser plays: closures and releases inserted, durations
 * fitted to the notes, syllable and word boundaries flagged. Lifted from
 * the original's machine code like the rest; see src/speech.c.
 */
#include "vw_engine.h"

'''

ORTH_EDITS = [
    ('    Dict dictHeader;', '    vw_DictFile dictHeader;'),
    ('        lo = dictHeader.hash[diff];', '        lo = VW_BE32(dictHeader.hash[diff]);'),
    ('        hi = dictHeader.hash[diff + 1] - 1;', '        hi = VW_BE32(dictHeader.hash[diff + 1]) - 1;'),
    ('        index = dictHeader.index;', '        index = VW_BE32(dictHeader.index);'),
    ('            fErr = FSRead(xx->dictFile, &inOutCount, &entryIndex);\n',
     '            fErr = FSRead(xx->dictFile, &inOutCount, &entryIndex);\n'
     '            entryIndex = VW_BE32(entryIndex);\n'),
    # the length of the phoneme string: a pointer difference stored in a byte
    ('    (*phon) = (int8_t)phonStr - (int8_t)phon - 1;', '    (*phon) = (int8_t)(phonStr - phon - 1);'),
]


def lift(*args):
    text = subprocess.check_output(
        [sys.executable, os.path.join(HERE, 'lift.py'), '--no-lines'] + list(args),
        cwd=ROOT).decode('utf-8').replace('\r\n', '\n')
    return '\n'.join(ln for ln in text.split('\n') if not ln.startswith('/* WARNING:'))


def edit(text, edits):
    for a, b in edits:
        assert text.count(a) == 1, a
        text = text.replace(a, b)
    return text


def prototypes(text):
    out = []
    for ln in text.split('\n'):
        if ln and not ln.startswith((' ', '}', '/', '#', 'static')) and '(' in ln and ln.endswith(')'):
            out.append(ln + ';')
    return out


def write(path, text):
    with open(path, 'w', newline='\n') as fh:
        fh.write(text)
    print('wrote', path, text.count('\n'), 'lines')


def main():
    orth = edit(lift('--unit', 'OrthToPhon.c'), ORTH_EDITS)
    parse = lift('--unit', 'ParsePhons.c')
    write(os.path.join(ROOT, 'src', 'orthtophon.c'), ORTH_PROLOGUE + orth.strip() + '\n')
    write(os.path.join(ROOT, 'src', 'parsephons.c'), PARSE_PROLOGUE + parse.strip() + '\n')
    hdr = ['/* vw_frontend.h -- the text front end: generated by tools/mkfront.py. */',
           '#ifndef VW_FRONTEND_H', '#define VW_FRONTEND_H', '',
           '/* OrthToPhon.c */'] + prototypes(orth) + ['', '/* ParsePhons.c */'] + \
        prototypes(parse) + \
        ['', '#endif /* VW_FRONTEND_H */', '']
    write(os.path.join(ROOT, 'include', 'vw_frontend.h'), '\n'.join(hdr))


if __name__ == '__main__':
    main()
